Make scripts a bit more reliable

diff --git a/scripts/fetch b/scripts/fetch
--- a/scripts/fetch
+++ b/scripts/fetch
@@ -19,7 +19,20 @@ do
   wget -O $f http://kotlinlang.org/$f
 done
 
+set +e
 wget --mirror --reject-regex 'api/latest/jvm/stdlib/org' -k -nH http://kotlinlang.org/docs/reference/
+wget_status=$?
+set -e
 
-wget -O - https://github.com/JetBrains/kotlin/archive/gh-pages.zip | bsdtar -xvf-
-mv kotlin-gh-pages _javadoc
+if [ $wget_status -eq 8 ]; then
+  # https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
+  echo "wget partially failed (exit status $wget_status)... continuing."
+elif [ $wget_status -ne 0 ]; then
+  echo "wget failed (exit status $wget_status)"
+  exit 1
+fi
+
+if [ ! -d _javadoc ]; then
+  wget -O - https://github.com/JetBrains/kotlin/archive/gh-pages.zip | bsdtar -xvf-
+  mv kotlin-gh-pages _javadoc
+fi
